# Generated by Django 3.1.2 on 2020-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardtab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('passwd', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('cont', models.TextField(blank=True, null=True)),
                ('bip', models.CharField(blank=True, max_length=20, null=True)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
                ('gnum', models.IntegerField(blank=True, null=True)),
                ('onum', models.IntegerField(blank=True, null=True)),
                ('nested', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boardtab',
                'managed': False,
            },
        ),
    ]
